chats_1 = [
    '@JACKSON_BIRZHA', '@youradvt', '@reclapoh', '@vpsmm_birzha', '@telegaAdmins',
    '@tolko_pokypka1', '@birzha_chat69', '@tgm_adm', '@reklama_chat_bazar', '@prgrps',
    '@cryptoadminsVP', '@pokupkatraff', '@prgrps', '@tg_chat3', '@telegaAdmins',
    '@kupi_prodai4', '@reklama_psychologi', '@KUPITrekyutyg', '@vp_kocmoc',
    '@market_bulls_and_bears', '@youradvt', '@cryptoadvt', '@birzha_reklamy23', '@birzha_reklami7',
    '@rekIama_chatt', '@reklama_chat_bazar', '@reclapoh', '@kleets', '@reklamakp',
    '@PRODVI1ZHENIE_REKLAMA', '@birjareklamitg', '@byrzha_reklamy2', '@tg_sale', '@milishatik',
    '@birzha_chat69', '@youradvt', '@birzha_reklamy22', '@birzha_reklamy_telegra', '@dvijenie_telegram',
    '@alice_bob_public', '@monopolistshop', '@reklamakp', '@youradvt', '@PRODVI1ZHENIE_REKLAMA',
    '@ads_blogger_chat', '@prgrps', '@active_birrrrrha', '@milishatik', '@vpsmm_birzha',
    '@active_birrrrrha', '@brt_tg2', '@telegaAdmins', '@birzhatgs', '@vp_kocmoc',
    '@vp_kocmoc', '@alice_bob_public', '@vp_kocmoc', '@market_bulls_and_bears', '@tg_chat3',
    '@ads_blogger_chat', '@vp_kocmoc', '@birzha_reklamy5', '@market_bulls_and_bears', '@brt_tg2',
    '@Reklamazdess', '@reklama_chat_bazar', '@market_bulls_and_bears', '@cryptoadminsVP', '@cryptoadvt',
    '@youradvt', '@dvijenie_telegram', '@PRODVI1ZHENIE_REKLAMA', '@tolko_pokypka1', 'brt_tg2',
    '@Reklamazdess', '@vp_kocmoc', '@reklama_chatic', '@alice_bob_public', '@rekwomen',
    '@market_bulls_and_bears', 'rekwomen', '@Reklamazdess', '@tg_sale', '@rekwomen',
    '@rekwomen', '@reklama_chatic', 'selrek', '@cryptoadminsVP', '@birjareklamitg',
    '@vp_kocmoc', '@tolko_pokypka1', '@hmonopolistshop', '@cryptoadminsVP', '@tgm_adm',
    '@birzha_chat69', '@tg_sale', '@PoznavalkiChat', '@BirzhaMCA', '@birzha_reklamy5',
    '@birga_ru', '@BirzhaWoman', '@brt_tg2', '@milishatik', '@brt_tg2',
    '@alice_bob_public', '@tgm_trade', '@birjareklamitg', '@vpdoc', '@dvijenie_telegram',
    '@vp_kocmoc', '@dvijenie_telegram', '@rekIama_chatt', '@KPP_telega', '@rekwomen',
    '@rekIama_chatt', '@youradvt', '@vp_kocmoc', '@youradvt', '@vp_kocmoc',
    '@chat_adminskiy_gaaaz', '@brt_tg2', '@market_bulls_and_bears', '@tg_chat3', '@hrekwomen',
    '@brt_tg2', '@tg_sale', '@brt_tg2', '@milishatik', '@birzha_chat69',
    '@vpdoc', '@reklamakp', '@ads_blogger_chat', '@youradvt@birzha_reklamy21', '@birzhahumor',
    '@adm_telegram', '@tolko_pokypka1', '@PoznavalkiChat', '@youradvt', '@birzha_reklami2',
    '@market_bulls_and_bears', '@ads_blogger_chat', '@selrek', '@trade_tgm', '@PRODVI1ZHENIE_REKLAMA',
    '@vpsmm_birzha', '@birzhatgs', '@PoznavalkiChat', '@rekwomen', '@reklama_psychologi',
    '@vp_kocmoc', '@telegaAdmins', '@vp_kocmoc', '@vp_chatik01', '@birzha_reklamy9',
    '@reklama_chatic', '@active_birrrrrha', '@alice_bob_public', '@tg_chat3', '@youradvt',
    '@QSAdmins', '@vp_kocmoc', '@Selfdevelop12', '@cryptoadvt', '@youradvt',
    '@alice_bob_public', '@birzha_reklamy_telegra', '@brt_tg2', '@youradvt', '@youradvt',
    '@monopolistshop', '@rekwomen', '@telegaAdmins', '@telegaAdmins', '@birzha_reklamy4',
    '@rekIama_chatt', '@tg_sale', 'AdHotChat', '@cryptoadminsVP', '@rekwomen',
    '@selrek', '@birjareklamitg', '@birzha_chat69', '@vpsmm_birzha', '@PRODVI1ZHENIE_REKLAMA',
    '@vp_kocmoc', '@milishatik', '@telegaAdmins', '@birga_ru', '@alice_bob_public',
    '@market_bulls_and_bears', '@cryptoadminsVP', '@alice_bob_public', '@cryptoadminsVP', '@rekwomen',
    '@vp_kocmoc', '@alice_bob_public', '@brt_tg2', '@telegaAdmins', '@kuply_poznavalka',
    '@PRODVI1ZHENIE_REKLAMA', 'brt_tg2', '@vpdoc', '@telegaAdmins', '@vp_kocmoc',
    '@kupi_prodai4', '@telegaAdmins', '@adm_telegram', '@cryptoadminsVP', '@birzha_reklamy3',
    '@milishatik', '@Reklamazdess', '@PRODVI1ZHENIE_REKLAMA', '@youradvt', '@birjareklamitg',
    '@cryptoadminsVP', '@alice_bob_public', '@vp_kocmoc', '@cryptoadminsVP', '@youradvt',
    '@vp_kocmoc', '@youradvt', '@brt_tg2', '@brt_tg2', '@brt_tg2',
    '@PRODVI1ZHENIE_REKLAMA', '@tgm_trade', '@alice_bob_public', '@ads_blogger_chat', '@dvijenie_telegram',
    '@rekwomen'
]



chats_2 = [
    '@telegaAdmins', '@telegaAdmins', "@monopolistshop", "@reklama_chat_bazar", "@tgm_adm", "@tg_chat3", 
    '@chat_adminskiy_gaaaz', '@market_bulls_and_bears', '@cryptoadminsV', '@cryptoadminsVP', '@PoznavalkiChat', 
    '@birzha_reklamy_telegra', '@Reklamazdess', "@reclapoh", '@PRODVI1ZHENIE_REKLAMA', '@birzha_reklamy22', 
    "@vpsmm_birzha", '@cryptoadminsVP', "@reclapoh", '@rekwomen', "@reklama_chat_bazar", '@PRODVI1ZHENIE_REKLAMA', 
    "@birzha_chat69", '@birzha_reklami7', '@birzha_reklamy_telegra', "@reklamakp", '@BirzhaMCA', "@birzhatgs", 
    '@milishatik', '@alice_bob_public', "@reklama_chatic", '@PRODVI1ZHENIE_REKLAMA', '@youradvt', '@brt_tg2', 
    '@market_bulls_and_bears', '@birjareklamitg', '@PRODVI1ZHENIE_REKLAMA', '@vp_doc', '@reklama_psychologi', 
    '@market_bulls_and_bears', '@kuply_poznavalka', "@tg_sale", '@PRODVI1ZHENIE_REKLAMA', '@vp_kocmoc', '@rekwomen', 
    "@monopolistshop", '@rekwomen', '@youradvt', '@vp_kocmoc', "@tg_chat3", "@Reklamazdess", "@AdHotChat", 
    '@market_bulls_and_bears', '@rekwomen', "@tgm_trade", '@brt_tg2', "@tgm_adm", '@PRODVI1ZHENIE_REKLAMA', 
    "@vpsmm_birzha", "@cryptoadvt", '@birzha_reklamy5', "@rekIama_chatt", '@birga_ru', "@vpdoc", "@trade_tgm", 
    "@kupi_prodai4", '@milishatik', '@milishatik', "@youradvt", "@monopolistshop", '@market_bulls_and_bears', 
    "@birjareklamitg", '@alice_bob_public', "@active_birrrrrha", '@alice_bob_public', '@youradvt', '@telegaAdmins', 
    '@brt_tg2', '@PRODVI1ZHENIE_REKLAMA', "@youradvt", '@KPP_telega', '@brt_tg2', "@tolko_pokypka1", 
    '@market_bulls_and_bears', '@ads_blogger_chat', '@birzhahumor', '@alice_bob_public', '@youradvt', 
    '@telegaAdmins', '@brt_tg2', '@birzha_reklamy2', "@birzha_chat69", '@birzha_reklamy21', '@youradvt', 
    '@birzha_reklamy23', '@PRODVI1ZHENIE_REKLAMA', '@brt_tg2', '@vp_kocmoc', '@reklama_chatic', '@birjareklamitg', 
    "@tgm_adm", '@vp_kocmoc', '@market_bulls_and_bears', '@market_bulls_and_bears', '@alice_bob_public', 
    '@telegaAdmins', '@alice_bob_public', '@alice_bob_public', "@tg_chat3", '@youradvt', '@milishatik', 
    '@Reklamazdess', "@reklama_chatic", '@alice_bob_public', "@tg_chat3", '@birzha_reklamy4', '@telegaAdmins', 
    '@cryptoadminsVP', "@birzhatgs", '@brt_tg2', '@rekwomen', '@alice_bob_public', "@vpsmm_birzha", 
    "@birjareklamitg", '@telegaAdmins', '@youradvt', '@brt_tg2', '@birzha_reklamy9', '@youradvt', '@youradvt', 
    "@birzha_chat69", "'@birjareklamitg", "@tg_sale", '@rekwomen', "@youradvt", '@cryptoadminsVP', "@tgm_trade", 
    "@kupi_prodai4", "@rekIama_chatt", '@youradvt', "@cryptoadvt", "@trade_tgm", "@ads_blogger_chat", 
    '@market_bulls_and_bears', "@tg_chat3", '@youradvt', '@youradvt', '@alice_bob_public', '@milishatik', 
    '@birzha_reklamy3', '@brt_tg2', '@telegaAdmins', '@VP_kocmoc', '@brt_tg2', '@alice_bob_public', '@vp_kocmoc', 
    '@cryptoadminsVP', '@brt_tg2', '@vp_kocmoc', '@brt_tg2', '@adm_telegram', '@brt_tg2', '@vp_kocmoc', 
    '@milishatik', '@brt_tg2', '@market_bulls_and_bears', '@birzha_reklamy5', "@monopolistshop", '@vp_kocmoc', 
    '@PRODVI1ZHENIE_REKLAMA', '@telegaAdmins', '@PRODVI1ZHENIE_REKLAMA', '@Reklamazdess', '@market_bulls_and_bears', 
    '@milishatik', '@VP_kocmoc', '@birzhaWoman', '@adm_telegram', '@youradvt', '@PRODVI1ZHENIE_REKLAMA', 
    '@market_bulls_and_bears', '@youradvt', '@youradvt', '@rekwomen', '@birga_ru', '@alice_bob_public', 
    '@alice_bob_public', '@adm_telegram', '@birzha_reklamy_telegra', '@vp_kocmoc', '@brt_tg2', '@milishatik', 
    '@brt_tg2', '@alice_bob_public', '@alice_bob_public', '@alice_bob_public', '@PRODVI1ZHENIE_REKLAMA', 
    '@rekwomen', '@market_bulls_and_bears', '@kupi_prodai4', '@alice_bob_public', '@rekwomen', '@telegaAdmins', 
    '@birzha_reklamy5', '@birzha_reklamy22', '@kleets', '@Reklamazdess', '@PRODVI1ZHENIE_REKLAMA', '@brt_tg2', 
    '@birzha_reklamy22', '@milishatik', '@brt_tg2', '@brt_tg2', '@alice_bob_public', "@market_bulls_and_b"
]



chats_3 = [
    '@PRODVI1ZHENIE_REKLAMA', "@rekIama_chatt", '@Reklamazdess', "@brt_tg2", "@monopolistshop", "@ads_blogger_chat", 
    "@vpdoc", "@ads_blogger_chat", '@alice_bob_public', '@youradvt', "@tg_chat3", '@birzha_reklami7',
    '@market_bulls_and_bears', '@brt_tg2', '@alice_bob_public', '@PRODVI1ZHENIE_REKLAMA', '@birzhaWoman', 
    '@PRODVI1ZHENIE_REKLAMA', '@PRODVI1ZHENIE_REKLAMA', '@rekwomen', '@PRODVI1ZHENIE_REKLAMA', '@brt_tg2', 
    '@PRODVI1ZHENIE_REKLAMA', "@active_birrrrrha", '@alice_bob_public', '@youradvt', '@PRODVI1ZHENIE_REKLAMA', 
    "@vpsmm_birzha", "@prgrps", "@birjareklamitg", '@Reklamazdess', "@tgm_trade", '@PRODVI1ZHENIE_REKLAMA', 
    "@cryptoadvt", "@kupi_prodai4", '@PRODVI1ZHENIE_REKLAMA', '@reklama_chatic', '@alice_bob_public', "@tg_chat3", 
    '@tgm_adm', '@alice_bob_public', '@alice_bob_public', '@birzha_reklamy3', '@PRODVI1ZHENIE_REKLAMA', '@youradvt', 
    '@alice_bob_public', '@alice_bob_public', "@youradvt", '@alice_bob_public', '@PRODVI1ZHENIE_REKLAMA', 
    "@birzhatgs", '@alice_bob_public', '@alice_bob_public', '@alice_bob_public', '@alice_bob_public', 
    '@PRODVI1ZHENIE_REKLAMA', "@AdHotChat", '@PRODVI1ZHENIE_REKLAMA', '@birzha_reklamy22', '@PRODVI1ZHENIE_REKLAMA', 
    "@birjareklamitg", '@reclapoh', "@prgrps", "@tg_chat3", '@youradvt', '@PRODVI1ZHENIE_REKLAMA', 
    '@PRODVI1ZHENIE_REKLAMA', '@PRODVI1ZHENIE_REKLAMA', '@tgm_adm', '@market_bulls_and_bears', "@selrek", 
    "@birzha_chat69", '@PRODVI1ZHENIE_REKLAMA', '@PRODVI1ZHENIE_REKLAMA', '@youradvt', "@birzhareklamy5", 
    "@youradvt", "@brttg2", "@rekwomen", "@trade_tgm", "@tolko_pokypka1", "@rekIama_chatt", "@birzhareklamy5", 
    "@PRODVI1ZHENIEREKLAMA", "@vpkocmoc", "@brttg2", "@rekwomen", "@telegaAdmins", "@ads_blogger_chat", 
    "@dvijenietelegram", "@birzhareklami7", "@cryptoadminsVP", "@chatadminskiygaaaz", "@birzhareklamy21", 
    "@marketbullsandbears", "@telegaAdmins", "@tg_sale", "@cryptoadvt", "@vpsmm_birzha", "@brttg2", 
    "@youradvt", "@telegaAdmins", "@youradvt", "@telegaAdmins", "@brttg2", "@reklamapsychologi", 
    "@AdHotChat", "@alicebobpublic", "@youradvt", "@birzhareklamy4", "@birzhareklami3", "@vpdoc", 
    "@alicebobpublic", "@kupiprodai4", "@PRODVI1ZHENIEREKLAMA", "@milishatik", "@Reklamazdess", "@tolko_pokypka1", 
    "@birzha_chat69", "@birzhareklamy9", "@byrzhareklamy2", "@youradvt", "@birzhareklamy22", "@Reklamazdess", 
    "@birzhareklamy23", "@prgrps", "@tgm_trade", "@alicebobpublic", "@active_birrrrrha", "@tg_chat3", 
    "@reklama_chatic", "@JACKSONBIRZHA", "@alicebobpublic", "@PRODVI1ZHENIEREKLAMA", "@tg_chat3", 
    "@ads_blogger_chat", "@pokupkatraff", "@birzhareklami2", "@rekwomen", "@birzhareklamy22", 
    "@PRODVI1ZHENIEREKLAMA", "@ads_blogger_chat", "@marketbullsandbears", "@birzhareklami5", "@tgsale", 
    "@birzhareklamy4", "@birzhareklamy23", "@telegaAdmins", "@vpkocmoc", "@birzhatgs", "@active_birrrrrha", 
    "@marketbullsandbears", "@kupi_prodai4", "@youradvt", "@alicebobpublic", "@prgrps", "@tolko_pokypka1", 
    "@birzhareklamy21"
]
